In [5]:
import tensorflow as tf
import numpy as np



tf.Tensor([12  2  3], shape=(3,), dtype=int32) : 2701226322048
tf.Tensor([22 12 13], shape=(3,), dtype=int32) : 2700455040448


In [18]:
# tensorflow 不可变
tfc = tf.constant([12,2,3])
print(tfc, ":", id(tfc))
tfc += 10
print(tfc, ":", id(tfc))

tfv = tf.Variable([12,2,3])
print(tfv, ":", id(tfv))
# tfv = tfv + 10 # new variable
# tfv.assign(10) # original variable
print(tfv, ":", id(tfv))


b = np.array([12, 2, 4])
print(b, ":", id(b))
b = b +  10
print(b, ":", id(b))

tf.Tensor([12  2  3], shape=(3,), dtype=int32) : 2701086647920
tf.Tensor([22 12 13], shape=(3,), dtype=int32) : 2701085221456
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([12,  2,  3])> : 2701213351216


ValueError: Cannot assign to variable Variable:0 due to variable shape (3,) and value shape () are incompatible

In [11]:
import tensorflow as tf
import numpy as np 

# f(x) = a*x**2 + b*x + c的导数

x = tf.Variable(0.0,name = "x",dtype = tf.float32)
a = tf.constant(1.0)
b = tf.constant(-2.0)
c = tf.constant(1.0)

with tf.GradientTape() as tape:
    y = a*tf.pow(x,2) + b*x + c
    print(type(y))
dy_dx = tape.gradient(y,x)
print(dy_dx, type(dy_dx))
print(type(x))

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(-2.0, shape=(), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [13]:
# 求f(x) = a*x**2 + b*x + c的最小值
# 使用optimizer.minimize
# optimizer.minimize相当于先用tape求gradient,再apply_gradient

x = tf.Variable(0.0,name = "x",dtype = tf.float32)

#注意f()无参数
def f():   
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    y = a*tf.pow(x,2)+b*x+c
    return y
ret = f()
print(type(ret))
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)   
for _ in range(1000):
    optimizer.minimize(f,[x])   

tf.print("y =",f(),"; x =",x)



<class 'tensorflow.python.framework.ops.EagerTensor'>
y = 0 ; x = 0.999998569
